# Generated by Django 5.0.4 on 2024-04-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=10)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('user_pass', models.CharField(max_length=10)),
            ],
        ),
    ]
